### ISSUE TITLE
how to use listStatusChanges to get envelopes that were sent to me?

### ISSUE THREAD

**Issue by teebu** [docusign/docusign-node-client#103]
I can only see the envelope status of envelopes I sent. What option is needed to include all the envelopes in the inbox?

**Comment by acooper4960** [comment]
envelopesApi.listDocuments is the call you are looking for. Please refer to the listDocuments unit test in SdkUnitTests for a sample of its usage

**Comment by LarryKlugerDS** [comment]
This [answer](https://stackoverflow.com/a/42303240/64904) from my colleague shows how you can list your incoming envelopes.

PS I'm sorry for the delay on answering this question. This type of question is best asked on stackoverflow with the `docusignapi` tag.
