### ISSUE TITLE
Is any change needed for the TLS 1.0 deprecation?

### ISSUE THREAD

**Issue by chris-fa** [docusign/docusign-node-client#104]
We've received notification of [TLS 1.0 deprecation](https://support.docusign.com/en/articles/DocuSign-is-deprecating-TLS-1-0-Encryption-Browser-Support). Since, by calling the API server, the library is a client to it; is this library going to be affected **in version 2.1.0**?  

If so, is there anything that can be done that doesn't involve updating its version?

**Comment by acooper4960** [comment]
@chris-fa You should be fine. Let me know if you have experienced any complications regarding this

**Comment by acooper4960** [comment]
I can confirm that the official release of Node handles this for you. No action needed
