### ISSUE TITLE
Apply locale to signers email?

### ISSUE THREAD

**Issue by guillaumegarcia13** [docusign/docusign-node-client#110]
It is unclear to me how to apply a locale to the email being sent to signers.

My understanding is that it is sufficient to append '&locale=fr' (for instance) to the end of the link under the CTA "REVIEW DOCUMENTS" but I could I achieve this using the NodeSDK?

**Comment by acooper4960** [comment]
Hi @guillaumegarcia13 Docusign automatically detects the signer's locale and handles this for you. 

Are you looking to set up a specific locale to override this behavior?
