### ISSUE TITLE
ConfigureJwtAuthorizationFlow Bad Request

### ISSUE THREAD

**Issue by Droppix** [docusign/docusign-node-client#111]
Hi,

I asked the question on stackoverflow for 4 days but no answer. [Here](https://stackoverflow.com/questions/51440009/docusign-configurejwtauthorizationflow-bad-request)

I am using DocuSign NodeJS SDK and using the below example to test authentication from Sample https://github.com/docusign/docusign-node-client#oauth-json-web-token-jwt-grant

I used this code with my parameters, and I obtain an error : BAD REQUEST My application is accepted by the Docusign server. (First time, I'm logged with website)

If I replace conf.docuSign.userID by "" (empty), the login is OK, I have an access_token, but I can't retrieve UserInfo.

`apiClient = new docusign.ApiClient();`
`apiClient.setBasePath(conf.docuSign.baseUrl);`
`docusign.Configuration.default.setDefaultApiClient(apiClient);`

`var oauthLoginUrl = apiClient.getJWTUri(conf.docuSign.clientID, `
`                                        conf.docuSign.redirectURI, `
`                                        conf.docuSign.oAuthBaseUrl);`

`// open DocuSign OAuth authorization url in the browser, login and grant access`
`logger.log('verbose', oauthLoginUrl);`

`let pathKey = path.resolve(conf.docuSign.privateKey);`
`apiClient.configureJWTAuthorizationFlow(pathKey, 
                                        conf.docuSign.oAuthBaseUrl, 
                                        conf.docuSign.clientID, 
                                        conf.docuSign.userID, 
                                        3600, function (err, res) 
{
    if (!err && res.body && res.body.access_token) {
        logger.log('verbose', "DocuSign OK");
    }
    else {
        logger.log('error', "DocuSign Error");
    }
});`

Any suggestion?

**Comment by acooper4960** [comment]
Hi Droppix,

Would it be possible for you to share with me your conf details pertaining to the oAuthBaseUrl you are using?

**Comment by Droppix** [comment]
Hi,

I call the function "apiClient.configureJWTAuthorizationFlow", and the return is :

- Err : Bad Request
- Response :
> Object {error: "consent_required"}
> error: Error: cannot POST /oauth/token (400)
> files: undefined
> forbidden: false
> header: Object {cache-control: "no-cache", pragma: "no-cache", content-type: "application/json; charset=utf-8", …}
> headers: Object {cache-control: "no-cache", pragma: "no-cache", content-type: "application/json; charset=utf-8", …}
> status: 400
> statusCode: 400
> statusType: 4
> text: "{"error":"consent_required"}"
> type: "application/json"
