### ISSUE TITLE
Template Access Code

### ISSUE THREAD

**Issue by ECDonelson** [docusign/docusign-node-client#112]
I know that a template access code can be set with Java, but how does it work the the Node.js client?

I've tried setting what I think the property would be but it doesnt yield the expected results.

Has anyone encountered this issue? Is there a fix for this issue? Last I spoke with someone at DocuSign's customer server center I was told this wasnt possible.

**Comment by acooper4960** [comment]
Hi @ECDonelson how exactly are you trying to set it?

access_code can be added to your envelopeTemplate postbody object in createTemplate to have it added

**Comment by acooper4960** [comment]
Hi @ECDonelson how exactly are you trying to set it, and what would be the specific java operation you are trying to find in the Node SDK?

**Comment by ECDonelson** [comment]
I found it.

For anyone who's curious (it took some digging in DocuSign's developer portal) but in order to set an access code in Node.js see the following: 

```
        var tempRole1 = new docusign.TemplateRole();
        tempRole1.roleName = recipient1RoleName
        tempRole1.name = recipient1FullName;
        tempRole1.email = recipient1Email;
        tempRole1.templateAccessCodeRequired = true;
        tempRole1.accessCode = 'access_code_here';
```

I didn't see anything implicitly stated in on github for the npm package so that's why I asked.
