### ISSUE TITLE
How do I populate a field on the Template I created

### ISSUE THREAD

**Issue by Hixme33** [docusign/docusign-node-client#113]
Created a Template, dragged a text box on the Template, gave it a Data Label Name of first_name.

How do I populate this field in code? 

I'm using the code in the SdkUnitTest.js as a guide.

Thanks!

**Comment by acooper4960** [comment]
@Hixme33 Hi there, we have some pretty easy examples to follow regarding this available for our hackathon'ers. Would you please take a look at https://github.com/DocuSign-Hackathons/getting-started and let me know if this has the solution are you looking for?
