### ISSUE TITLE
Is anyone else having issues with intellisense in vs code and cs 2017?

### ISSUE THREAD

**Issue by johnmeister** [docusign/docusign-node-client#115]
For some reason Im getting 0 instellisense options with both vs code and vs 2017. Anything I can do?

**Comment by acooper4960** [comment]
Which object are you trying to use intellisense on? I am unable to reproduce your issue in vscode and sublime

**Comment by johnmeister** [comment]
im on node version 10.1.0
 "dependencies": {
    "async": "^2.6.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.9",
    "docusign-esign": "^4.0.2",
    "dotenv": "~6.1.0",
    "ejs": "~2.5.7",
    "express": "~4.16.0",
    "http-errors": "~1.6.2",
    "morgan": "~1.9.0",
    "request": "^2.88.0"
  }
}

**Comment by acooper4960** [comment]
Does intellisense work with other editors for you?

**Comment by acooper4960** [comment]
I can't help you with your editor issues, maybe open a ticket with microsoft?

**Comment by johnmeister** [comment]
Ok, thanks. Just thought I’d ask if anyone else had the problem. Ill try uninstalling and reinstalling the package / vs code and see what happens.
