### ISSUE TITLE
Consider generating your code into TypeScript

### ISSUE THREAD

**Issue by robpaveza** [docusign/docusign-node-client#116]
I'm looking at this project - https://github.com/mikestead/openapi-client - and considering whether it would be possible / useful to leverage TypeScript, since the other project can generate TypeScript. Unfortunately you emit a type `number`, which requires manual renaming of that interface in the TypeScript output.

When you transpile, this will emit a .d.ts file which can be specified via package.json - this will give really rich IntelliSense in supported editors.

This seems like it would also help address #115 as well.

**Comment by Carbonneau** [comment]
I know this is closed, But i was wondering if you have considered publishing an @types/docusign-esign for NPM. This would greatly improve the dev experience. Thanks!

**Comment by proletesseract** [comment]
@types/docusign-esign for NPM would be very helpful.

**Comment by hypeofpipe** [comment]
☝️

**Comment by hypeofpipe** [comment]
@acooper4960 the link seems to be broken

**Comment by johnmeister** [comment]
Any Update? Really sucks not have any intellisense.

**Comment by maxcan** [comment]
@hypeofpipe  https://raw.githubusercontent.com/docusign/eSign-OpenAPI-Specification/master/esignature.rest.swagger-v2.1.json

**Comment by maxcan** [comment]
@hypeofpipe @johnmeister @robpaveza if you drop the above json file into https://editor.swagger.io, you can get decently reasonable types

**Comment by equimbo** [comment]
I have published the docusign-esign typings we used at https://www.npmjs.com/package/@types/docusign-esign

**Comment by Kinqdos** [comment]
@equimbo Thank you for sharing your types, unfortunately the types are two major versions behind. Would you mind publishing an updated version to support version 7.x.x?
