### ISSUE TITLE
Question: what effect does authenticationMethod have when used in envelopesApi.createRecipientView

### ISSUE THREAD

**Issue by jwugit** [docusign/docusign-node-client#118]
The authenticationMethod field, used in createRecipientView function, offer a list of options but does it do anything to the generated URL access?
Changing between none, email and password doesnt seem to add any security when i click on the url to sign. Is it suppose to do anything?

**Comment by LarryKlugerDS** [comment]
The `authenticationMethod` field is set by the developer and is later shown in the envelope's certificate of completion.

The purpose of the field and the related fields of `assertionId`, `authenticationInstant`, `clientUserId`, and `securityDomain` are to enable you, the developer, to establish as many facts as possible about the veracity of the signature. 

When you use createRecipientView, the developer has the first level of responsibility for authenticating the signer. If you want, you can also have DocuSign perform additional authentication checks such as 2FA via SMS message, Knowledge Based Authentication, etc. But the first level of authentication can be done by your app. These fields enable you to record the details of your authentication check.

Recording the method and details of how you authenticated the signer is important in case of disputes--both for preventing forgery (someone else signed) and repudiation (I signed but now I claim that I didn't sign.)

PS. I am sorry that your question was not answered before now. For future questions of this sort, please use StackOverflow and our `docusignapi` tag. Thank you.
