### ISSUE TITLE
Tests are very fragile

### ISSUE THREAD

**Issue by Whoaa512** [docusign/DocuSign-Node-Client#12]
The tests rely on way too much external state to be useful. They should be mocked out use [`nock`](https://www.npmjs.com/package/nock) not only to run faster but to also run reliably.

**Comment by nikmash** [comment]
We figured it would be a good source of truth to know if the API responses change. But you're right we should convert them to be mocked out. I can work on mocking with nock.

**Comment by Whoaa512** [comment]
I agree with that sentiment. We should probably have a set of tests which are run against the live API as well.

Also be sure to check out [nock's recording](https://www.npmjs.com/package/nock#recording) feature

**Comment by Whoaa512** [comment]
Fixed in #35 & #34

**Comment by alexpchin** [comment]
What happened to the mocked tests? Have they now been removed?
