### ISSUE TITLE
Cannot set the value of a text tab with Numbers validation

### ISSUE THREAD

**Issue by sanjucta** [docusign/docusign-node-client#126]
I have a text tab on my template with Numbers validation. When I try to use the nodejs sdk to populate that field, I am unable to do it. 

My code looks like this .
let demolition = docusign.Text.constructFromObject({
                                tabLabel: "Demolition", value: args.demolition});

let builderTabs = docusign.Tabs.constructFromObject({
                    textTabs: [owner1Name,owner2Name,ownerEmail,ownerMailingAddr,ownerTel,ownerMobile
                              ,ownerFax,totalPrice,propertyAddr,witnessName], 
                    numberTabs: [demolition]         
                                                 }); 

The error that I receive from the API is : 
text: '{\r\n  "errorCode": "UNSPECIFIED_ERROR",\r\n  "message": "Object reference not set to an instance of an object."\r\n}',

**Comment by LarryKlugerDS** [comment]
Hi @sanjucta,
Are you still having this problem? 

I think it is related to internal ticket DCM-2732 -- Bug: the Node.js SDK currently does not support Number tabs.

**Comment by sanjucta** [comment]
Hi @LarryKlugerDS , 

Yes, I still have this problem :(
Sanjucta

**Comment by acooper4960** [comment]
Hi @sanjucta Have you tried declaring a numberTab and assigning that to your numberTabs array? 

From this example it appears you are assigning a Text field to your numberTabs array

**Comment by acooper4960** [comment]
Hi @sanjucta this issue has been resolved in the upcoming v4.3.0. An rc is available on npm, and can be accessed via npm install docusign-esign@next, please let us know if this resolves your issue

**Comment by sanjucta** [comment]
@acooper4960 , thank you for the update. I don't get an error anymore when trying to set the value of a text tab with Numbers validation. And if I set the value to a valid number , the value is set correctly as expected. So that is indeed resolved.
However, if I try to set it to a value that is not a number , it still sets the value , so the number validation does not work, In the code below whether I set myvalue to 100 or to "not a number" the field gets set correctly.

let myvalue = 100;
//let myvalue = "not a number";

let demolition = docusign.Text.constructFromObject({
tabLabel: "Demolition", value: myvalue});

let builderTabs = docusign.Tabs.constructFromObject({
textTabs: [owner1Name,owner2Name,ownerEmail,ownerMailingAddr,ownerTel,ownerMobile
,ownerFax,totalPrice,propertyAddr,witnessName],
numberTabs: [demolition]
});

If I try 
let myNum = docusign.Number.constructFromObject({
                                tabLabel: "numbersOnly", value: myVal});

Then there is a runtime error :
TypeError: Cannot read property 'constructFromObject' of undefined

**Comment by acooper4960** [comment]
Hi @sanjucta glad to hear it works for you now. 
Yes it would be nice to have more type checking client side, however this is more related to swagger codegen itself and may be something in the future we might propose to them.

That being said, we do handle all type checking server side.  For the clients it is more up to the responsibility of the consumer to perform these.

Another piece of advice that could help when initializing these child properties. I would recommend staying away from constructFromObject unless you are trying to convert directly from json. 

Initializing the objects from the models themselves and then assigning them to the parent will give you better control over this proces as well as some nice to haves, such as autocompletion.

Please see test, 'create template with date and number tabs', located in [https://github.com/docusign/docusign-node-client/blob/v4.3.0-rc1/test/SdkUnitTests.js](https://github.com/docusign/docusign-node-client/blob/v4.3.0-rc1/test/SdkUnitTests.js)
for an example.

**Comment by LarryKlugerDS** [comment]
Try

````
let myNum = docusign.ModelNumber.constructFromObject({
    tabLabel: "numbersOnly", value: myVal});
````
Instead of "Number"

Thanks,
Larry
