### ISSUE TITLE
Upgrading package from 4.0.2 to 4.2.2 breaks the app in production

### ISSUE THREAD

**Issue by canho123** [docusign/docusign-node-client#129]
I upgraded the package `docusign-esign` from `4.0.2` to `4.2.2`. B/c it was a `minor` upgrade so I were assuming that it shouldn't break the application. In fact, it works fine for all environments except for `production`. The reason is that in the old version (4.0.2), it uses directly the value set from the application (oAuthBasePath) which is `account.docusign.com`:

```javascript
superagent('post', 'https://' + oAuthBasePath + '/oauth/token')
      .timeout(this.timeout)
      .set('Content-Type', 'application/x-www-form-urlencoded')
```
In the upgraded version `4.2.2`, the previous code becomes:

```javascript
superagent('post', 'https://' + this.getOAuthBasePath() + '/oauth/token')
      .timeout(this.timeout)
```

and the ` getOAuthBasePath()` just return the value which is calculated from `deriveOAuthBasePathFromRestBasePath`:

```javascript
var deriveOAuthBasePathFromRestBasePath = function(basePath) {
    if (basePath == null) {
      return exports.prototype.OAuth.BasePath.PRODUCTION;
    }
    if (basePath.includes('https://stage')) {
      return exports.prototype.OAuth.BasePath.STAGE;
    }
    if (basePath.includes('https://demo')) {
      return exports.prototype.OAuth.BasePath.DEMO;
    }
    if (basePath.includes('https://www.docusign')) {
      return exports.prototype.OAuth.BasePath.PRODUCTION;
    }
  };
```
The `basePath` argument from `deriveOAuthBasePathFromRestBasePath` when in execution receives value `account.docusign.com`. As a result the `deriveOAuthBasePathFromRestBasePath` return `null` and thus breaks the app.

**Comment by acooper4960** [comment]
Hi @canho123 this issue has been resolved in the upcoming v4.3.0. An rc is available on npm, and can be accessed via npm install docusign-esign@next, please let us know if this resolves your issue
