### ISSUE TITLE
why did you delete this function ? EnvelopesApi.createViewLink

### ISSUE THREAD

**Issue by arceus-jia** [docusign/docusign-node-client#132]
v2/accounts/{accountId}/envelopes/{envelopeId}/views/viewlink
this api is still work, but function is missing

Thanks

**Comment by LarryKlugerDS** [comment]
We no longer encourage developers to use that method. Instead, download the document to your own application and then provide it to your users as needed.

At this time we have no plan to remove the API call. But we have removed the documentation and SDK support.
