### ISSUE TITLE
Unable to import docusign-esign into App.js file. Module not Found errors. [How to set up your SPA with DocuSign]

### ISSUE THREAD

**Issue by Animanny** [docusign/docusign-node-client#143]
I have a basic `create-react-app` application that I'm trying to import docusign into. I have run the 
```Bash
$ npm i docusign-esign
```
 command to add the dependency to the project and then required the dependency as such
```Javascript
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
const docu = require('docusign-esign');
```

However, I'm seeing issues when this require line is included:
```Bash
Module not found: 'model/EnvelopesInformation' in /Users/asrikanth/Documents/testing/my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/ErrorDetails' in /Users/asrikanth/Documents/testing/my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/EventNotification' in /Users/asrikanth/Documents/testing/my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/EventResult' in /Users/asrikanth/Documents/testing/my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/Expirations' in /Users/asrikanth/Documents/testing/my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/ExternalDocServiceErrorDetails' in /Users/asrikanth/Documents/testing/my-app/node_modules/docusign-esign/src

 @ ./~/docusign-esign/src/index.js 15:4-9950

Error in ./~/docusign-esign/src/index.js
Module not found: 'model/ExternalFile' in /Users/asrikanth/Documents/testing/my-app/node_modules/docusign-esign/src
```

and so on with about every requirement of the `docusign-esign/src/index.js` file. 
I did run an npm install after adding it and that doesn't fix it. How could I resolve this?

**Comment by acooper4960** [comment]
Hi @Animanny, which version of docusign-esign are you running?

**Comment by Animanny** [comment]
I believe my `package.json` says 5.0.2

Yes, I've tried that to no avail. I've noticed that it works when it's not in a react-app. Is this is a known issue?

**Comment by acooper4960** [comment]
@Animanny so it appears you are importing docusign-esign into your client code. However, DocuSign doesn't not support CORS. Try accessing the package inside of you server code

**Comment by acooper4960** [comment]
@Animanny so it appears you are importing docusign-esign into your client code. However, DocuSign doesn't not support CORS. We have a good article on how best to set this up for your SPA here: https://www.docusign.com/blog/dsdev-building-single-page-applications-with-docusign-and-cors-part-1/ 
https://www.docusign.com/blog/dsdev-building-single-page-applications-with-docusign-and-cors-part-2/

**Comment by m-czyz** [comment]
Its also a problem in backend webpack (we use aws lambda)

**Comment by bhanu-alapati** [comment]
It is still an issue in AWS lambda build where we are also using webpack.

**Comment by jimmyn** [comment]
I have the same issue with webpack in AWS lambda
