### ISSUE TITLE
No documentation for includeHMAC on EventNotification

### ISSUE THREAD

**Issue by naten3** [docusign/docusign-node-client#144]
This flag seems to do exactly what I want. I'd like to use this in production and I'd like the other developers on my project to believe it's official functionality. Can we get it added? 

http://docusign.github.io/docusign-node-client/module-model_EventNotification.html

**Comment by acooper4960** [comment]
Hi @naten3 Glad to see this is working as expected. I am unsure what you are asking here. Could you please clarify?

**Comment by naten3** [comment]
Just that it be documented in the EventNotification model linked above. I think that's the correct object right? I only found it looking through the source code.

**Comment by acooper4960** [comment]
We have a new release in flight, scheduled for next week. I will make sure this update is included in it for you guys

**Comment by acooper4960** [comment]
Correct, this is a valid object. It is new to our SDK and documentation is still being added for it. We will have new docs with it out next week, but a more detailed description of its functionality can be found here. https://developers.docusign.com/esign-rest-api/guides/connect-hmac

**Comment by acooper4960** [comment]
@naten3 v5.1.0 is now in the RC phase. As such we have new documentation up on github.io. You should see includeHMAC now listed as a member of this model.
