### ISSUE TITLE
Remove Unsupported Expiration Methods from EnvelopeDefinition

### ISSUE THREAD

**Issue by aust1nz** [docusign/docusign-node-client#154]
This SDK's docs list a few expiration-related members directly on the [EnvelopeDefinition](http://docusign.github.io/docusign-node-client/module-model_EnvelopeDefinition.html) object that don't seem to map to the actual Docusign API or have any effect. Specifically, this concerns:

- expireAfter
- expireDateTime
- expireEnabled

In my testing, these values have no effect on the sent envelope, and expireDateTime in particular seems to promise functionality that doesn't exist -- Docusign only allows users to set the expiration in number of days, as an integer.

The following code _does_ work:

```
envDef.notification = docusign.Notification.constructFromObject({
      expirations: {
        expireEnabled: true,
        expireAfter: '1'
      }
    });
```

If I'm just misunderstanding the documentation, I'd appreciate clarity. Otherwise, I suggest removing the members mentioned above from the otherwise very informative documentation for this SDK.

**Comment by acooper4960** [comment]
Hi @aust1nz which version of the SDK are you using?

**Comment by aust1nz** [comment]
Hi, I'm using version 5.1.0. More broadly, I can't find any reference to the Docusign API supporting an expireDateTime type of function.

**Comment by acooper4960** [comment]
For undocumented parameters such as this, I would recommend staying away from them until documentation has been written for them. They are typically either in beta, or in progress of being hidden in the future.
