### ISSUE TITLE
apiClient.callApi: Superagent Warning If Callback Is Supplied

### ISSUE THREAD

**Issue by ZacharyDraper** [docusign/docusign-node-client#155]
The apiClient.callApi() function has an option to supply a callback as a parameter; however, if you do so, the following message will appear in the console:

```
Warning: superagent request was sent twice, because both .end() and .then() were called. Never call .end() if you use promises
Warning: .end() was called twice. This is not supported in superagent
(node:840) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
superagent: double callback bug
```

This issue then trickles down to all functions that use callApi() and pass in a callback, such as envelopesAPI.createEnvelope().

**Comment by acooper4960** [comment]
Hey @ZacharyDraper could you send me some sample code showing how you are passing this callback?

**Comment by ZacharyDraper** [comment]
Sure. Here is an example through the envelopesAPI.createEnvelope()

```
let results = await envelopesApi.createEnvelope(
	config.accountID,
	{envelopeDefinition: envelope},
	function(error, data, response){
		console.log('here');
	}
);
```

**Comment by acooper4960** [comment]
Hi @ZacharyDraper yes so the syntax you are providing indicates that you are both sending a callback and expecting a Promise to be returned. That is why you are getting this error. Please choose just one method of async and try again.

**Comment by ZacharyDraper** [comment]
You are correct. Sorry about that.

I could not get the system to return any data (or throw an error or anything) from envelopesAPI.createEnvelope() or envelopesAPI.createRecipientView() so after looking at the source code, I tried adding the callback in an attempt to learn more from the response, but I neglected to remove the 'await' keyword before it. Removing that keyword does resolve this error.

I am still not getting any errors or data from either of these functions, but at least now I can output the response object (which does have data) and can hopefully learn something from that.

**Comment by acooper4960** [comment]
@ZacharyDraper good luck, and feel free to checkout the SDKUnitTests.js files for some sample code regarding calling this method with either promises or callbacks

**Comment by asad-shakeel** [comment]
The same error occurred to me, my use case was:
```js
        (...request)
        .expect(200, (error) => console.log(error))
        .expect(({ body: { data, errors } }) => {
```
I was using callback 2 times 1 in each `expect` block.

I removed the unnecessary callback from the 1st `expect` block and it is now working fine.
```js
        (...request)
        .expect(200)
        .expect(({ body: { data, errors } }) => {
```
