### ISSUE TITLE
recipientSuppliesTabs gets set to true on one recipient of my template

### ISSUE THREAD

**Issue by hgrubst** [docusign/docusign-node-client#156]
I have a template with 3 signers from which I create an envelope.
My issue is that with 1 recipient in particular, the field recipientSuppliesTabs gets set to true and this recipients gets a free form signing experience.

I have tried supplying recipientSuppliesTabs : false in the templateRoles when creating the envelope but this does not do anything. Does the api not support this field ?

**Comment by acooper4960** [comment]
hey @hgrubst yes this property is not yet supported
