### ISSUE TITLE
sendEnvelope does not support many available request parameters

### ISSUE THREAD

**Issue by distracteddev** [docusign/DocuSign-Node-Client#16]
First off, thanks for maintaining an official Node.js client! 

Second, if I'm reading the source correctly, it seems like the `Envelopes.sendEnvelope` function only supports the recipient, files, and subject request params. 

In particular, I'm interested in the EventNotification param, but was wondering if you'd see any problem with me simply adding an `additionalParams` argument to the `sendEnvelope` function signature that would get merged into the request body before sending (https://github.com/docusign/DocuSign-Node-Client/blob/master/components/envelopes.js#L294)?

_All params listed [here](https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Send%20an%20Envelope.htm%3FTocPath%3DREST%2520API%2520References%7CSend%2520an%2520Envelope%2520or%2520Create%2520a%2520Draft%2520Envelope%7C_____0)_

**Comment by Whoaa512** [comment]
I like the idea! Could you send a PR with the changes and jsdoc changes? I'll review it asap

**Comment by distracteddev** [comment]
Thanks for this!
