### ISSUE TITLE
Missing getPdfBlob function

### ISSUE THREAD

**Issue by alex88** [docusign/docusign-node-client#200]
In your documentation you have a function that seems be able to download the pdf blob of an envelope http://docusign.github.io/docusign-node-client/module-api_EnvelopesApi.html#getPdfBlob

However I can't find it in the code, is it from an unreleased version?

**Comment by LarryKlugerDS** [comment]
I'm sorry for the late reply.

That documentation is from an old SDK version from Aug 28 2019 -- that's the date of the docs.

For downloading docs from DocuSign, see the https://github.com/docusign/code-examples-node repository and example workflow [eg007EnvelopeGetDoc.js](https://github.com/docusign/code-examples-node/blob/master/lib/examples/eg007EnvelopeGetDoc.js) it demonstrates how to download a document from DocuSign.

**Comment by alex88** [comment]
Hi @LarryKlugerDS thank you! In the meantime I've been using that and it's working fine
