### ISSUE TITLE
Signer with Witness & Witness - How to create via API?

### ISSUE THREAD

**Issue by kay-es** [docusign/docusign-node-client#201]
Hey,

I'm currently facing the issue that I'm not able to define a "Signer with Witness" and a "Witness" for a given Template. If I set the recipientTypes to signer and witness and also link them as the template lists it (signers, ccs and witnesses), both (signer and witness) appear as signer which are not linked.

I tried this with the sdks for nodejs and also java.

Example for nodejs:
```
let signer1 = docusign.TemplateRole.constructFromObject({
        email: "signer@bbb.com",
        name: "Signer",
        roleName: 'Signer 1',
        recipientId: "1",
        routingOrder: "1",
        recipientType: "signer"
    });

    let witness1 = docusign.TemplateRole.constructFromObject({
        email: "witness@bbb.de",
        name: "Witness (Witness for Signer)",
        roleName: "Witness 62074759 for 1",
        witnessFor: "1",
        recipientType: "witness",
        recipientId: "62074759",
        routingOrder: "1"
    })
```

Is this "feature" currently only working via the UI? Any ideas how to work around? I guess the relevant fields are not set to the envelope.

Regards and thanks in advance
Kay

**Comment by LarryKlugerDS** [comment]
Please see my [StackOverflow answer](https://stackoverflow.com/a/61431348/64904) for adding the witness feature.
If you have more questions, please open a question on StackOverflow with the `docusignapi` tag.
Thank you,
Larry
