### ISSUE TITLE
Docs improvement: NodeJS script for  generating a JWT Token.

### ISSUE THREAD

**Issue by Santiago8888** [docusign/docusign-node-client#215]
Hi, I've been trying to generate the token for programmatic as stated on this guide:
https://developers.docusign.com/docs/platform/auth/jwt/jwt-get-token/#Create

But I simply have not had success, and keep getting` invalid_request ` as an error response:

There are a couple of things that concern me on the guide:
1. You request a user account ID, in my API & Keys Pannel I have **User ID** & **API Account ID** I'm guessing is the first, but you can understand my confusion.
2. In the example JWT, you're passing a "name" parameter but on the body definition, you are not mentioning it. Should I pass it or not? What is the name from the user, or from the account?
3. The param exp, mentions it defaults to one hour but it also mentions that is required. Also, it says that cannot be set to more than one hour, but in the example JWT it is set to more than an hour.
4. Finally, on the sample JWT, you're declaring in the signature that a dot separates the public and private keys. Most signature packages I encountered use a colon "," instead:
```
RSASHA256(
  base64UrlEncode(-----BEGIN PUBLIC KEY-----
MIIBIj...IDAQAB
-----END PUBLIC KEY-----) + "." +
  base64UrlEncode(-----BEGIN RSA PRIVATE KEY-----
MIIEpQ...9ZwKY=
-----END RSA PRIVATE KEY-----),
```

This last issue leads me to think, that I'm possibly encountering a bug. Please help @acooper4960

**Comment by Santiago8888** [comment]
I've enabled logs in security preferences but it only contains my web navigation history. 

I also tried in the troubleshooting section, in the same guide. But the response I'm getting is not included, the closest there it is: "Invalid authentication request: The response type is not supported", but mentions a different issue.

**Comment by Santiago8888** [comment]
I really do not understand where the error was in my previous attempts, but here is a Node script that get's the job done. 

I hope it helps someone, and maybe it can be added to the docs, because using curl as the docs currently suggest do not return the error_description.

```
const jwt = require('jsonwebtoken');
const moment = require('moment');
const axios = require('axios');
const fs = require('fs');

const grant_type = 'urn:ietf:params:oauth:grant-type:jwt-bearer'
const privateKey = fs.readFileSync('private.key')
const clientId = "<your-application-client-id>"
const userId = "<your-user-id>"

const claims = {
  iss: clientId,
  sub: userId,
  iat: moment().unix(),
  exp: moment().add(60, 'minutes').unix(),
  aud: "account-d.docusign.com",
  scope: "signature impersonation"
}

jwt.sign(claims, privateKey, { algorithm: 'RS256' }, (err, assertion) => {
    if (err) console.log(err)
    
    console.log(assertion);
    const body = { grant_type, assertion };    

    axios.post('https://account-d.docusign.com/oauth/token', body)
    .then(({data}) => console.log(data))
    .catch(({response}) => console.log(response.data));
});

```

As for my questions:
1. Yes, is the User Id, not the API Id.
2. The name is not required, the sample JWT body requires an update.
3. The exp claim is indeed required and needs to be valid (less than one hour of difference with the iat). However, the value is dismissed when generating the token. I suggest updating the sample (with a valid difference) and replacing the "Defaults to one hour" wording for "is set to one hour". Even better remove the claim, or use it when generating the token.
4. As for the last point, fortunately, no bugs to report :)

**Comment by Santiago8888** [comment]
Actually the entirety of the code is already on the [tests](https://github.com/docusign/docusign-node-client/blob/9f5e3c6e3ea76e03b9d22b90fe1d1eab6d46ab1a/test/SdkUnitTestsWithCallback.js). It's just a matter of creating documentation from them.

`var oauthLoginUrl = apiClient.getJWTUri(integratorKey, RedirectURI, oAuthBasePath);
`

**Comment by annesophien** [comment]
Hi @Santiago8888, I apologize for the delayed response and thank you for bringing this to our attention and for providing suggestions to improve our docs. It seems you have already found answers to your questions. Please reach out if you need further assistance. 

As for documentation, I've created DEVDOCS-3429 for our docs team to address these concerns.

**Comment by Santiago8888** [comment]
Indeed @annesophien, my questions were solved and using the API. Good luck, with the Docs update!

Feel free to close.

**Comment by acooper4960** [comment]
Closing this issue for now. Thanks for checkout out SDKUnitTests for docusign-node-client specific inquiries @Santiago8888, that is usually where we direct customers for questions such as this.
