### ISSUE TITLE
Error: returnUrl parameter must not exceed 500 characters when calling createRecipientViewPromise

### ISSUE THREAD

**Issue by rleachpear** [docusign/docusign-node-client#224]
Getting a `400` error from DocuSign when calling `createRecipientViewPromise`

```
    body: {
      "errorCode": "INVALID_REQUEST_PARAMETER",
      "message": "The request contained at least one invalid parameter. 'returnUrl' parameter must not exceed 500 characters."
    }
```

The following url triggered the error, which has a length of **480**. 
```
http://localhost:3000/survey?flow_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiRUdOci9MeGViNmRUMVRVQVRZOXNvYndPTWNEcnZ4QVdncDI0dWNwazVmRzBxZ2t4RDRIaTFtM2RUcnJZdVVmbHFhc3JnSmtHT1hoZ0FodWdpNEEramQ4QTg0K2ZxNTBKaTFWOG5rYi9LRFdwVmw3OVVvSlBzOE9wY3FZMHNIOD0iLCJpbml0aWFsaXphdGlvblZlY3RvciI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzIzOSwxNTIsMjUyLDE5NSwxNjAsNTAsOTEsMTg5LDExMywxNzEsMTUzLDE4MiwxNTgsMjcsODEsMTc3XX0sImlhdCI6MTYwMTA0Nzk0NH0.fp-zKByfrAX2EOkoEqTAstCyjs-YOZOArW843U4CHSM
```

We have verified that our returnUrl does **not** exceed the 500 character limit as indicated by the error message.

Able to reproduce in our development environments where our demo account is being used. This does not seem to happen in production with our paid account.

**Comment by jkohne-ds** [comment]
@rleachpear Apologies in the delay in response. Thank you for bringing this to our attention. Just so we can better understand the scenario, can you clarify what you're trying to accomplish with the flow_token parameter being passed along in the redirect URL?

**Comment by rleachpear** [comment]
@jkohne-ds Our `flow_token` param is just our encoded identifier which contains context for the system the signer is returning to. I think that's a pretty common use-case for that param.

I think this ticket can be closed. I have been in contact with Docusign API support and they confirmed that there was a difference between how their demo environment was validating the returnUrl vs the production environment. In demo, validation was on be default whereas in production it is off. The resolution on their side was to turn off validation in demo (for now).

From Support:
> Engineering confirmed that my understanding is correct, the go forward default will be to have Url length validation turned off in the REST API. We have added logging in this area, and if engineering finds that a bunch of customers are using more than 500 characters they may flip the default in the future. If that happens open a case and we can get a dynamic system setting change made for you to turn it off in your account.

The issue still remains that the 500 character validation is calculating against a string where values are introduced outside the control of the calling code such that the _actual_ length appears to be more like **474**.

From Support:
> I think what is happening is we are calculating the the additional characters of the event string we add- "&event=signing_complete" - and padding the number.

This may be something this client library should keep in mind for the future as it looks likely to pop up again.
