### ISSUE TITLE
PDF form field transformation set Text Field as required (non-empty value)

### ISSUE THREAD

**Issue by Santiago8888** [docusign/docusign-node-client#225]
Hi again,

I've been using [PDF form field transformation](https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/tabs/pdf-transform) to add tab fields, in particular, name, company, and date. Thankfully, they are working great, now, I need to add a new field "Location" that would be translated as a text field. However, I see the new field labeled as "optional".

On the [DocuSign Community](https://support.docusign.com/s/question/0D51W000069k6IgSAI/mandatory-text-field), I see that text fields should be set as mandatory. However, that does not appear to be the case, as I can submit an envelope with an empty value, event dismissing it completely.

From the API I can see that tabs, can be created and [updated](https://developers.docusign.com/docs/esign-rest-api/reference/Envelopes/EnvelopeDocumentTabs/update/) but when I'm trying to make the request to update the tab as required I get:
`"errorCode":"UNSPECIFIED_ERROR","message":"Object reference not set to an instance of an object."`.

Given that the API Reference does not specify what fields are required and which not I have doubts as to how to actually make the request.

**Comment by Santiago8888** [comment]
Thank you @ivdinkov, you might be right that the PDF form transformation might have different behavior.

And yes, I was trying the UPDATE endpoint (as referenced in the link), I managed to debug the `"UNSPECIFIED_ERROR"  ` but I still haven't succeeded on enforcing the field as required. The possible reasons for this I believe  are:

1. There is no clear mapping between a particular on the PDF document and on the DocuSign envelope. I'm using the name, that in the Adobe PDF specification is supposed to be unique, however, DocuSign might use another internal field to map between tags.
 
2. I'm using the update more like a PUT, in the sense that I only specify the name and the `required` field that I'm interested in setting. DocuSign might be requiring additional fields to be added to the request. However, I'm not getting an error during the request, so I believe this is less likely.

3. For text fields, in particular, I might be needing another attribute besides the `required` attribute, given that an empty string as a value might be treated as non-null. However, when signing the Document, I see a tooltip marking the field as "Optional" as opposed to "Required" so that might neither be the case.

**Comment by ivdinkov** [comment]
I am not sure what lang you use, but here is my example
The way I tested this was by creating envelope as a **draft** and then 
I used this is the code:
`            string envelopeId = "your envelope id";

            var recipientList = envelopesApi.ListRecipients(accountId, envelopeId);
            var tabList = envelopesApi.ListTabs(accountId,envelopeId,recipientList.Signers.FirstOrDefault().RecipientId.ToString());
            var theOne = tabList.TextTabs.Where(t => t.Name == "the name from the pdf you want to update").FirstOrDefault();
            theOne.Required = "true";

            Tabs newTabs = new Tabs();
            List<Text> newTextList = new List<Text>();
            newTextList.Add(theOne);
            newTabs.TextTabs = newTextList;

            Tabs result = envelopesApi.UpdateTabs(accountId,envelopeId,recipientList.Signers.FirstOrDefault().RecipientId.ToString(),newTabs);
`

**Comment by Santiago8888** [comment]
Thank you @ivdinkov, looks great! I'm also using TypeScript. 
I'll test your solution in a couple of hours and get back to you

**Comment by Santiago8888** [comment]
Hi, @ivdinkov. I see now, that you are not using TypeScript but rather C#.
Unfortunately, when attempting to update the status of the draft, from created to sent. I'm facing a malformed response error response:
`{"errorCode":"INVALID_REQUEST_BODY","message":"The request body is missing or improperly formatted."}`

I tried this, following the first example of the [envelope update API request](https://developers.docusign.com/docs/esign-rest-api/reference/Envelopes/Envelopes/update/):
`await envelopesApi.update(this.accountId, envelope.envelopeId, { status: 'sent' });`

The same happens with an updated body, similar to the one used during the create envelope request. 

I do not know how is the situation with C# is but on TypeScript the available published types for the SDK have a type of `any` for the options to be provided to the UPDATE envelope request, that leaves me with little to no guidance as to how to form the request:


Additionally, **I'm facing a second issue with the transform PDF method.** 

The requirement I'm trying to meet is to send a carbon copy of the envelope before it is signed.

From the [docs](https://support.docusign.com/en/guides/ndse-user-guide-signing-order) I see that to send a carbon copy before the envelope is signed I need to set the `routingOrder` with a lower value than the signer's recipient. In this case, the carbon-copy would get a `routingOrder` value of "1" while the signer's recipient, a value of "2".

When the envelope is sent, the sending order works as expected, with both, the carbon copy recipient and the signer receiving each an unsigned envelope, the issue is, that the envelope's PDF document form values are distorted. In particular, the values are lost from the form fields that were disabled (in the original PDF document), and the form fields that are supposed to be converted into DocuSign tags are not, as if the `transformPdfFields` property was omitted. In case, it helps, the carbon copy is watermarked with a legend of "In Progress" which hopefully indicates a possible cause of the issue.

Should I open a second issue for this? For us, this second issue has a very high priority, and I'm happy to provide help to debug/reproduce the issue. Finally, while we hope to keep using the `transformPdfFields` method for setting the tags, would you advise us to consider a different method?

**Comment by ivdinkov** [comment]
Hi @Santiago8888, I think it will be better to move this thread away as it is getting to big and I may need you to provide some extra info. Please if you can send an email to go-live@docusign.com with link ref to this issue and my name. This will create internal case and I will be able to follow up then

**Comment by ivdinkov** [comment]
1. `Envelope tempEnv = new Envelope();
            tempEnv.Status = "sent";
            var envelopeStatusUpdate = envelopesApi.Update(accountId, envelopeId, tempEnv);`
2. `Settings > Sending Settings > When an envelope is sent, write the initial value of the field for all recipients`

**Comment by Santiago8888** [comment]
Thank you for your help @ivdinkov. Closing this as solved.
