### ISSUE TITLE
Account ID Inconsistency in request headers

### ISSUE THREAD

**Issue by distracteddev** [docusign/DocuSign-Node-Client#29]
During the Docusign certification process, I was notified that it seems like for multi-part requests, we are sending the actual AccountId as the header, instead of the Guid. 

This is just a FYI. Not critical to be changed, but would be nice for it to be consistent.

From my initial investigation, it seems to be caused by the different methods used to construct the headers between dsUtils.makeRequest and dsUtils.sendMultipart

**Comment by Whoaa512** [comment]
Sorry, can you show me where the `AccountId` is added to the headers? I was looking through both uses of `sendMultipart` and I can't seem to figure out where or why an account id would ever be in the headers. 

I'm gonna add some debug logging to see if I can track this down.
