### ISSUE TITLE
promisification breaking sendEnvelope

### ISSUE THREAD

**Issue by brynwaldwick** [docusign/DocuSign-Node-Client#33]
https://github.com/docusign/DocuSign-Node-Client/blob/master/components/envelopes.js#L106

This promisification is breaking the sendEnvelope function used w/ a callback as implemented here https://www.docusign.com/developer-center/quick-start/request-signatures

I was able to get it to work properly by making it sendEnvelope(<args>).asCallback(callback) like most of the other methods.

**Comment by Whoaa512** [comment]
Thanks, missed that in my refactor. Expect a published fix shortly

**Comment by Whoaa512** [comment]
fixed in v7.0.2
