### ISSUE TITLE
Docusign hangs when making a sendTemplate request even though a response is received

### ISSUE THREAD

**Issue by ignasg** [docusign/DocuSign-Node-Client#37]
Using the example from introduction. It seems like the issue is in here as the request callback is not passed into the method
```
return dsUtils.makeRequest('Send Template', options);
```

The following method update seems to do the trick:
```
add
 * @param {function} [callback] - Returns the response body from DS API
add parameter at the end:
function sendTemplate (apiToken, baseUrl, emailSubject, templateId, templateRoles, additionalParams, callback) {

add parameter at the end
return dsUtils.makeRequest('Send Template', options, callback);
```
Make sure to update the example as  follows
```
client.envelopes.sendTemplate(subject, templateId, templateRoles, null, function (err, response) {
```

**Comment by Whoaa512** [comment]
Nope, the example in the readme was just out of date.

See the `sendTemplates` function signature here: http://docusign.github.io/DocuSign-Node-Client/Envelopes.html

**Comment by Whoaa512** [comment]
To clarify, the error was not in missing the callback, but in missing the additionalParams argument.
