### ISSUE TITLE
What changed from 6.0 - 7.0?

### ISSUE THREAD

**Issue by distracteddev** [docusign/DocuSign-Node-Client#38]
Without a changelog, how are we supposed to know what changed and if we can safely upgrade our API clients? 

Also, is this package practicing proper semver versioning? (https://nodesource.com/blog/semver-a-primer/)

**Comment by Whoaa512** [comment]
Most notably in 7.0 the seamless promise interface was added(`5595925`). In a previous version we began supporting promises through the use of bluebird's wonderful `promisifyAll` which had the unfortunate side-effect of duplicating each method and adding an `-Async` suffix.

7.0 saw the removal of this way of doing things and thus a cleaner interface was achieved albeit at the  cost of making a breaking change.

To answer your other question, yes this repo does follow proper semver and will not hesitate in bumping the major version for even the most slightest of breaking changes.
