### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by Whoaa512** [docusign/DocuSign-Node-Client#4]
I think it's hard to get even the tests running since even before you can, you need to:
- create an envelope
- create a template

It would be useful to new consumers of this module to have a guide for how to do this programmatically using this module.

**Comment by nikmash** [comment]
Great idea! I will add a convenience function to do so. Definitely would help developers get started with the package.

**Comment by Whoaa512** [comment]
Fixed in #34 & #35

See the `examples` folder and all the tests
