### ISSUE TITLE
Wrong function signature for update()

### ISSUE THREAD

**Issue by PatrickHeneise** [docusign/docusign-node-client#49]
https://github.com/docusign/docusign-node-client/blob/master/src/api/EnvelopesApi.js#L643

This is completely misleading. According to API definition, `envelope` should be the options where I can set the status to 'sent', and `options` is completely irrelevant, making it difficult to know which one the callback parameter is.

```
envelopesApi.update(accountId, envelope.id, {
        status: 'sent'
      }, {}, (error, data) => {
      });
```

**Comment by mmallis87** [comment]
Patrick, Sorry for late response. I don't see why it's irrelevant. Can you be more specific? The docs looks clear to me about what option is for: https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/update/

You might also be interested to try this call, use the new API explorer (beta): https://apiexplorer.docusign.com/#/?categories=Envelopes&tags=Envelopes&operations=update

**Comment by mmallis87** [comment]
No news from the reporter. Closing the issue.
