### ISSUE TITLE
Script to get initial `config.json` values

### ISSUE THREAD

**Issue by Whoaa512** [docusign/DocuSign-Node-Client#5]
It's unclear how one is supposed to get the values for:
- `DOCUSIGN_TEST_ENVELOPE_ID` 
- `DOCUSIGN_TEST_TEMPLATE_ID`
- `DOCUSIGN_TEST_TEMPLATE_ROLE`

To improve the first user experience when running tests or trying this module out, it would be useful to have a script which gets this values and populates them in the `config.json`

**Comment by nikmash** [comment]
Definitely and I believe this ties into https://github.com/docusign/DocuSign-Node-Client/issues/4.

**Comment by Whoaa512** [comment]
Invalid since now we have `test-config.json` with dummy accounts
