### ISSUE TITLE
PDF form fields are not detected by DocuSign

### ISSUE THREAD

**Issue by vasyldemchuk** [docusign/docusign-node-client#51]
I have a PDF file with form fields.
I have successfully uploaded pdf template, but fields are not detected by DocuSign for some reason.
Are there any options which I need to turn on/off? Please advice.

**Comment by Ergin008** [comment]
Hi @vasyldemchuk 

There is indeed a property that you need to set to have the platform convert your PDF form fields into DocuSign tabs, it's called `transformPdfFields` and it's a member of the **documents** node inside the envelope definition.  

More info here:  [Document Parameters](https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST API References/Document Parameters.htm?Highlight=transform)

**Comment by mmallis87** [comment]
@vasyldemchuk does Ergin's answer solved your problem. Please share you update.

**Comment by vasyldemchuk** [comment]
Hi @mmallis87

Unfortunately setting `transformPdfFields:"true"` did not solve the issue.
My post request looks like the following:

```
{
"envelopeTemplateDefinition":{"name":"name"}, 
"documents: [{
    "documentId":"1", 
    "uri":null, 
    "remoteUrl":null, 
    "name":"CustomFields.pdf", 
    "password":null,
    "transformPdfFields":"true",
    "fileExtension":null,
    "matchBoxes":[],
    "order":null,
    "pages":null,
    "documentFields":[],
    "encryptedWithKeyManager":null,
    "documentBase64:"blablabla", 
    "applyAnchorTabs":null}],
.......
}
```
Also I tried to play around (set to `true/false`) `defaultRecipient` option for the `signers`, but without any luck.
Let me know if you have other ideas what is wrong there. Thanks a lot.

**Comment by Ergin008** [comment]
Hi @vasyldemchuk , as I read into the documentation more here I think I remember how this works.  Sorry I haven't had time to test yet, but I think this is what's going on: 

There are two different ways you can use the `transformPdfFields` property.  As the page I referenced states, when using it on a document in the documents array[] it has the effect of transferring the *values* that you've pre-populated your PDF fields with into existing DocuSign tabs, as long as the names of the PDF fields match the corresponding `tabLabel` of the DocuSign tabs.  

If you are trying to do a straight transformation of PDF form fields into DocuSign tabs (like the website does) then you still use the `transformPdfFields` property but you need to do it in the context of a composite template.  

Not sure if you're using a template or not as that determines if you use the `serverTemplates` node or not, assuming you're not try something along these lines:

	{	
    	"emailSubject": "please sign this doc",
    	"status": "sent",
    	// other potential envelope properties
		"compositeTemplates": [
		{
            "inlineTemplates": [
                {
                    "sequence": "1",
                    "recipients": {
        				"signers": [{
            				"email": "john@email.com",
            				"name": "John Doe",
            				"recipientId": "1",
            				"defaultRecipient": "true"
            			}]
            		}	
                }
            ],
            "document": {
                "documentId": "123",
                "name": "Contract.pdf",
                "transformPdfFields": "true"               
            }
        }]	
    }

**Comment by Ergin008** [comment]
Yeah I just tested this and got it to transform the PDF form fields, try matching up your request to the following JSON:

	{
		"status": "sent",
		"emailSubject": "Tranform PDF Fields example",
		"recipients": {
			"signers": [{
				"email": "john@email.com",
				"name": "Jon Dough",
				"recipientId": "1"
			}]
		},
		"compositeTemplates": [{
			"inlineTemplates": [{
				"sequence": "1",
				"recipients": {
					"signers": [{
						"email": "john@email.com",
						"name": "Jon Dough",
						"recipientId": "1",
						"defaultRecipient": "true"
					}]
				}
			}],
			"document": {
				"documentId": "1",
				"name": "test.pdf",
				"documentBase64": "1",
				"transformPdfFields": "true"
			}
		}]
	}

**Comment by mmallis87** [comment]
@vasyldemchuk did @Ergin008's solution work for you? If not, please tell us why.

**Comment by mmallis87** [comment]
Haven't heard back from the reported for a while. closing the issue. please re-open in case the issue persists.
