### ISSUE TITLE
Getting access to the API limit headers

### ISSUE THREAD

**Issue by BertrandFritsch** [docusign/docusign-node-client#54]
According to this page https://www.docusign.com/p/APIGuide/Content/Introduction+Changes/API%20Call%20Limits.htm, DocuSign adds headers (X-RateLimit-XXX) to some HTTP responses to control the API calls per hour.
Is there a way to get access to those headers when using the functions of the docusign-node-client module?

**Comment by mmallis87** [comment]
Look inside the "response" object, returned by the API call (ApiClient.callApi). For example:

envelopesApi.createEnvelope(accountId, envDef, null, function (err, envelopeSummary, response) {
      if (err || !response) {
        return next(err);
      }
      console.log('API calls remaining: ' + response.header['X-RateLimit-Remaining']);
      next(null);
    });

**Comment by mmallis87** [comment]
@BertrandFritsch Does that helps?

**Comment by BertrandFritsch** [comment]
Sorry for the late answer, but I was confused. It seems that I don't use the sources from this repository.
I use the NPM module from https://www.npmjs.com/package/docusign, which badly points to this repository.

Indeed, this module provides the right way to get access to the API call rate headers.

Thanks.

**Comment by mmallis87** [comment]
@BertrandFritscg docusign module is old and will be deprecated soon, as it is not maintained, doesn't support the new versions of our API and have only a small range of API features.

The new module "docusign-esign", which is built from this github repo is recommanded.

By the way, we are going to release a passport package for DocuSign OAuth very soon. We encourage developers to use OAuth to call DocuSign APIs. The examples and recipes might be changed to use OAuth as well. In the mean while, OAuth is documented in our documentation portal: https://docs.docusign.com
