### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by gurunadh5** [docusign/docusign-node-client#55]
Is these node module builtin   implementation of DocuSign  rate limit or not?

**Comment by mmallis87** [comment]
Look inside the "response" object, returned by the API call (ApiClient.callApi). For example:

envelopesApi.createEnvelope(accountId, envDef, null, function (err, envelopeSummary, response) {
if (err || !response) {
return next(err);
}
console.log('API calls remaining: ' + response.header['X-RateLimit-Remaining']);
next(null);
});

**Comment by gurunadh5** [comment]
Thanks for your respone. Is any rate limit algorithm in these node modules?I want to restrict the api calls.

**Comment by mmallis87** [comment]
@gurunadh5 Sorry, but I'm not sure I get your point. We don't have another node module yet, but if you can you give me more details, I can check if it's possible to make it work with the current module or consider adding the feature in case it's missing.

**Comment by gurunadh5** [comment]
@mmallis87 
I  would like to embed the signing into my app (Embedded Signing) through the API rather than opening DocuSign in another window.  I will also want to invoke the DocuSign Multi-factor authentication feature.Could you please let me know how to implement (Embedded Signing) through the API using template?
 
Please find below details in Docusign Api limitations.
**API Rules and Limits**

To maintain reliability and stability within our demo and production environments DocuSign has the following API rules and rate limits in place. The 20+ test transactions needed to go live, as well as any transactions sent in production, must comply with the following platform rules. Violation of these rules may result in your Integrator Key being disabled for a period of time.

You may not exceed 1,000 API requests per account per hour.
You may not exceed 1 status request per unique envelope per 15 minutes.
You may not exceed 1 unique document request per unique envelope per 15 minutes.
The following REST and SOAP calls qualify as status or document requests:

REST API: GET /accounts/{accountId}/envelopes/...
SOAP API: RequestStatus, RequestStatusEx, RequestStatuses, RequestStatusesEx,RequestPDF and RequestDocumentPDFs
For example, the following set of requests are in violation of API rules since more than 1 GET request is made on envelope AAA within 15 minutes:

[12:00:00] POST /accounts/12345/envelopes
[12:01:00] GET  /accounts/12345/envelopes/AAA 
[12:02:00] POST /accounts/12345/envelopes
[12:03:00] GET  /accounts/12345/envelopes/BBB
[12:04:00] GET  /accounts/12345/envelopes/AAA *
The following transactions also violate API rules due to the repeated GET requests to the first document and second recipient:

[12:00:00] POST /accounts/12345/envelopes
[12:01:00] GET  /accounts/12345/envelopes/AAA/documents/1
[12:02:00] GET  /accounts/12345/envelopes/AAA/recipients/2
[12:03:00] POST /accounts/12345/envelopes
[12:04:00] GET  /accounts/12345/envelopes/AAA/documents/1 *
[12:05:00] GET  /accounts/12345/envelopes/AAA/recipients/2 *
However the following set of requests comply with API rules and limits and would not be flagged by the platform:

[12:00:00] POST /accounts/12345/envelopes
[12:01:00] GET  /accounts/12345/envelopes/AAA
[12:16:00] GET  /accounts/12345/envelopes/AAA
[12:17:00] GET  /accounts/12345/envelopes/AAA/documents/1 
[12:32:00] GET  /accounts/12345/envelopes/AAA/documents/1 
[12:40:00] PUT  /accounts/12345/envelopes/AAA/recipients/1
[12:41:00] PUT  /accounts/12345/envelopes/AAA/recipients/1

**Comment by LarryKlugerDS** [comment]
I'm sorry for the very slow response to your question. We have re-organized to improve response time.

To answer your question, your application should look at the response headers to check the API limits.

For embedded signing, see scenario 1 in the [code examples launcher](https://github.com/docusign/eg-03-node-auth-code-grant).
