### ISSUE TITLE
API does not conform to the Node.js style of error passing

### ISSUE THREAD

**Issue by Whoaa512** [docusign/DocuSign-Node-Client#6]
The API this module implements is very inconsistent throughout the code base. Sometimes calling callbacks with error first, other times wrapping the error in a plain object and sticking it on an error property. 

This goes against the standard of always passing errors as the first parameter to any callback, and this module should be refactored to follow that standard.

Also there seems to be a pattern of passing strings as errors, when in fact a custom error class should be used instead.

**Comment by cbeiter** [comment]
Thanks CJ.  We noticed this also while developing the 1.0 of the package that we were inconsistent and tried to address some of them.  

This is definitely something we want to address.  What are your thoughts on the priority of this?

**Comment by Whoaa512** [comment]
I believe this to be a major priority in terms of adoption of the SDK by Node.js developers. No one will give this a second look if they see an obvious ignorance of the common Node patterns.

Have no fear though, I'm in the middle of a significant refactor to remedy this

**Comment by Whoaa512** [comment]
I would say that it's very important from an adoption perspective. I'm actually in the middle of a refactor to remedy this and will submit a PR once done :)



Cheers,
CJ
