### ISSUE TITLE
"errorCode": "USER_AUTHENTICATION_FAILED" after changing email address

### ISSUE THREAD

**Issue by alexpchin** [docusign/docusign-node-client#67]
I'm passing the updated email address with the old password, but now I receive USER_AUTHENTICATION_FAILED. 

Do I need to do something more in order to pass authentication after changing my email address?

**Comment by mmallis87** [comment]
You just need to make sure to use the good combination of username and password, if it works in Sandbox login they it should work in the API, independent of which Integrator Key you pass in.

**Comment by alexpchin** [comment]
Thanks, I'm probably doing a stupid typo somewhere. I'll close. I've been working on this Docusign integration for a while. Am I able to email you directly with some further (less silly) questions?

**Comment by mmallis87** [comment]
@alexpchin Unfortunately we don't have direct support for Sandbox accounts. The best way is to post questions on StackOverflow using docusignapi tag: https://stackoverflow.com/questions/tagged/docusignapi

You can also search in the existing questions. Good luck!

**Comment by alexpchin** [comment]
@mmallis87 Thanks for the response. I've been looking at Stackoverflow actually to no avail... I just can't seem to get the right setup to pre-populate information in a template, send to multiple recipients and for all of the recipients to see the pre-populated fields. E.g. Property Address in a rental contract for both Tenant & Landlord...

I'm finding the docs and examples really quite tricky to navigate.

**Comment by mmallis87** [comment]
@alexpchin look at the free sample app, it has some examples that are a bit close to what you're trying to do: https://github.com/docusign/docusign-node-client#sample-app
