### ISSUE TITLE
Display SecureField initial value to all recipients via API

### ISSUE THREAD

**Issue by alexpchin** [docusign/docusign-node-client#68]
In order to show the contents of tabs to other signers, I had to move from the new docusign UI to the classic one and then go to `Preferences > Features` and turn on `Display SecureField initial value to all recipients`

<img width="412" alt="screen shot 2017-05-23 at 13 38 59" src="https://cloud.githubusercontent.com/assets/40461/26354831/457dc5cc-3fbe-11e7-9b5d-a8bf0fe4d95b.png">

Is is possible to do this with the API? Because I've lost about 3 days looking for this and it is extremely unclear.

**Comment by mmallis87** [comment]
There is a company initiative in place to move all the preferences from Classic UX to the new UX and make them more user-friendly. This flag is not available through the API and out of the scope of the Node SDK.

**Comment by alexpchin** [comment]
Does this not do the same thing?

### PUT /v2/accounts/{accountId}/settings

```
{
  "accountSettings": [
    {
      "name": "signerShowSecureFieldInitialValues",
      "value": "true"
    }
  ]
}
```
