### ISSUE TITLE
Missing a standardized style

### ISSUE THREAD

**Issue by Whoaa512** [docusign/DocuSign-Node-Client#7]
This can be easily fixed using either [standard](https://www.npmjs.com/package/standard) or [semistandard](https://www.npmjs.com/package/semistandard)

I should have a couple of PRs in shortly to address this. Feel free to merge whichever one fits you guys best

**Comment by nikmash** [comment]
Perfect. I think we're more of Semi standard people.

**Comment by Whoaa512** [comment]
Yea I figured as much :)
