### ISSUE TITLE
Proxy Server 

### ISSUE THREAD

**Issue by rajarv** [docusign/docusign-node-client#71]
Our severs behind firewall, how to setup the proxy server for the API client

**Comment by Sushindhran** [comment]
Any solutions for this?

**Comment by rajarv** [comment]
You need to use the superagent-proxy.   Patched the API client file to support proxy.

**Comment by acooper4960** [comment]
Hello, 

An update regarding this ticket. We have an internal branch adding proxy support with superagent-proxy. However, in order to maintain support for Node version 4 and 5 we are unable to include this at this time. This ticket has been targeted for the next major upgrade of this package.

**Comment by acooper4960** [comment]
A branch with proxy support has now been added with v5.1.0. 

Please take a look at branch v5.1.0-Proxy for this. Keep in mind, that in order to add this capability, support or Node.js v4 and v5 has been dropped on this branch.
