### ISSUE TITLE
CoreRecipes.js is outdated

### ISSUE THREAD

**Issue by rlataguerra** [docusign/docusign-node-client#72]
examples in file https://github.com/docusign/docusign-node-client/blob/master/test/Recipes/CoreRecipes.js are outdated

**Comment by mmallis87** [comment]
thanks for reporting that. We're actually looking into that and they should be updated as soon as we can. In the meanwhile please check the test cases here: https://github.com/docusign/docusign-node-client/blob/master/test/SdkUnitTests.js

**Comment by HancePatrick** [comment]
Loved the code look and feel in CoreRecipes.js, but as said earlier, it's STILL outdated (4.5 months later).   Having issues getting past first step with SdkUnitTests.js, like Cannot find module '../src/index'.   What is it, where to get it?

**Comment by benrolfe** [comment]
Can the `CoreRecipes.js` file be marked as legacy, as it's confusing to have a broken code example. For example `setDocumentBase64` doesn't exist as a function.

**Comment by LarryKlugerDS** [comment]
I apologize that we have not been more responsive. We've re-organized to improve.

I have removed the Core Recipes repo from public display.

For Node.js, here are the recommended sets of examples:

Recommended:  [Authorization Code Grant example launcher and scenarios](https://github.com/docusign/eg-03-node-auth-code-grant)

[JWT Grant authentication example](https://github.com/docusign/eg-01-node-jwt)
