### ISSUE TITLE
Outdated Dependency

### ISSUE THREAD

**Issue by javarebel** [docusign/docusign-node-client#76]
Any plan to upgrade dependency superagent (1.7.1)? Superagent (1.7.1) brings qs(2.3.3) as a dependency which has a security vulnerability [(https://snyk.io/vuln/npm:qs:20170213?utm_campaign=vuln_alert&utm_medium=email&utm_source=Vuln).](https://snyk.io/vuln/npm:qs:20170213?utm_campaign=vuln_alert&utm_medium=email&utm_source=Vuln)

**Comment by mmallis87** [comment]
@javarebel Thank you for reporting the vulnerability in the dependency. I created a hotfix branch and upgraded the outdated packages, which should bring a safe version of qs as well. The new version of this package will be pushed to NPM in the next days.

**Comment by mmallis87** [comment]
version 3.2.1 of this package is finally out.
