### ISSUE TITLE
What's the latest and the stable version of the client?

### ISSUE THREAD

**Issue by chris-fa** [docusign/docusign-node-client#79]
I see master branch is different from `8.x.x` tag. Also there are branches like `8.x.x` and `oauth`. Which one should I be using for production? 

Assume I'll install `npm install docusign-esign --save`, I assume the package installed is the one from master branch? or which one?

**Comment by mmallis87** [comment]
As indicated in the NPM registry, the last version is 3.2.1 and it is stable and recommended: https://www.npmjs.com/package/docusign-esign

You can also the timeline of releases (from latest to oldest) here: https://github.com/docusign/docusign-node-client/releases
