### ISSUE TITLE
Incorrect consent URL

### ISSUE THREAD

**Issue by MathiasMeuleman** [docusign/docusign-node-client#81]
Hi there,

While testing with this API, I ran into an issue. There seems to be a small mistake while generating the consent URL in `ApiClient.getJWTUri`. It is my believe that the URI component that is encoded should be changed from `signature+impersonation` to `signature impersonation`, rendering an encoded URI component `signature%20impersonation` instead of `signature%2Bimpersonation`, in complience with the documentation. This at least fixed things for me.

**Comment by MathiasMeuleman** [comment]
Just in case this isn't clear: the resulting behaviour is that Docusign only asks me to grant Signature scope permissions, not Impersonation scope permissions. while that is the case if I manually change to URL.

**Comment by mmallis87** [comment]
@MathiasMeuleman Thank you for reporting this. I made the changes already. Tests are passing so it should hit NPM pretty soon. I will close this once it's out there.

**Comment by MathiasMeuleman** [comment]
Perfect!
