### ISSUE TITLE
Using callbacks

### ISSUE THREAD

**Issue by ECDonelson** [docusign/docusign-node-client#86]
Is there a better way to utilize callbacks other than async.waterfall([])?

I need to archive rows of data after the envelope is made and sent, and there doesnt seem to be a documented way that doesnt use async.waterfall that actually works.

**Comment by mmallis87** [comment]
It's up to you. It's matter of code style. I suggest using Promises: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by ECDonelson** [comment]
That doesnt answer my question on how to implement it.

I understand what a promise is, but what's an example of a promise being used with docusign?

**Comment by mmallis87** [comment]
@ECDonelson I haven't tried it but Promisification, using a library like Bluebird, could help use this SDK methods as promises. See http://bluebirdjs.com/docs/api/promisification.html
