### ISSUE TITLE
Not fulfilling callback without break-point

### ISSUE THREAD

**Issue by ECDonelson** [docusign/docusign-node-client#88]
Third issue I've put up this week.

I've talked it over with another developer and this should work:

 function archiveRequest() {
      var callback = archiveAlertMessage;
      var selectedRows = gridOptions.api.getSelectedRows();
      var index = 0;
      var count = selectedRows.length - 1;

    archiveNextRow();

    function archiveNextRow() {
        var accepted = validateUserInput(selectedRows[index], 'archiveRequest');

        if (accepted && accepted.length == undefined) {
            if (selectedRows.length == 0) {
                archiveAlertMessage()
            } else {
                if (selectedRows[index].DocuSignID != '' && selectedRows[index].DocuSignID != undefined) {
                    createTemplate(selectedRows[index], function (error, envelopeSummary, response) {
                        if (error) {
                            console.log(error);
                            alert(error);
                        } else {
                            console.log(JSON.stringify(envelopeSummary));
                            console.log(JSON.stringify(response));
                            return sendToUltiProAndArchive(selectedRows[index], afterDataArchive);
                        }
                    });

                } else {
                    archiveAlertMessage();
                }
            }
        } else {
            selectedRows[index].BenefitDate = '';
            selectedRows[index].NewType = '';
            selectedRows[index].TransferToLocation = '';
            selectedRows[index].TransferToStoreNbr = '';
            selectedRows[index].EffectiveDate = oldValue;
            selectedRows[index].EffTransDate = '';

            gridOptions.api.updateRowData({ update: selectedRows });

            confirm('The program encountered the following issues: ' +
                '\n\n' + (accepted[0] ? accepted[0] : '') +
                '\n' + (accepted[1] ? accepted[1] : '') +
                '\n' + (accepted[2] ? accepted[2] : '') +
                '\n' + (accepted[2] ? accepted[3] : '') +
                '\n' + (accepted[2] ? accepted[4] : '') +
                '\n' + (accepted[2] ? accepted[5] : '') +
                '\n\n Please correct the above issues in order to continue.');
        }
    }

    function afterDataArchive(err, returnValue) {
        if (err) {
            confirm(err.message);
        }

        if (index >= count) {
            callback();
        } else {
            index += 1;
            archiveNextRow();
        }
    }

    function archiveAlertMessage() {
        if (selectedRows.length == 1) {
            alert('Your request has been sent to DocuSign. You can finish the job change process by submitting this request on the UltiPro tab.');
        } else if (selectedRows.length > 1) {
            alert('Your requests have been sent DocuSign. You can finish the job change process by submitting this request on the UltiPro tab.');
        } else {
            alert('You must select a row to sent to DocuSign.');
        }
    }
}

function createTemplate(selectedRow, callback) {
    // put variables needed for multiple functions here and they will be captured in the closure
    var creds = JSON.stringify({
        Username: email,
        Password: password,
        IntegratorKey: integratorKey
    });
    apiClient.addDefaultHeader('X-DocuSign-Authentication', creds);

    var authApi = new docusign.AuthenticationApi(apiClient);
    var loginOps = {};
    loginOps.apiPassword = 'true';
    loginOps.includeAccountIdGuid = 'true';

    return afterConfigApiClient();

    function afterConfigApiClient() {
        debugger;
        return authApi.login(loginOps, afterLogin);
    }

    function afterLogin(error, loginInfo, response) {
        console.log(loginInfo);
        var loginAccounts = loginInfo.loginAccounts;
        var loginAccount = loginAccounts[0];
        var accountId = loginAccount.accountId;
        var baseUrl = loginAccount.baseUrl;
        var accountDomain = baseUrl.split("/v2");
        // below code required for production, no effect in demo (same domain)
        apiClient.setBasePath(accountDomain[0]);
        docusign.Configuration.default.setDefaultApiClient(apiClient);

        return sendTemplate(loginAccount);
    }

    function sendTemplate(loginAccount) {
        // create a new envelope object that we will manage the signature request through
        var envDef = new docusign.EnvelopeDefinition();
        //TODO add associate name here
        envDef.emailSubject = 'Please sign Special Wage Review sheet for ' + selectedRow.AssociateName;
        envDef.templateId = templateId;

        //TODO add the other template roles here
        // create a template role with a valid templateId and roleName and assign signer info
        var signer1 = new docusign.Signer();
        signer1.email = recipient1Email;
        signer1.name = recipient1FullName;
        signer1.recipientId = '1';

        var tempRole1 = new docusign.TemplateRole();
        tempRole1.roleName = recipient1RoleName
        tempRole1.name = recipient1FullName;
        tempRole1.email = recipient1Email;

        var signer2 = new docusign.Signer();
        signer2.email = recipient2Email;
        signer2.name = recipient2FullName;
        signer2.recipientId = '2';

        var tempRole2 = new docusign.TemplateRole();
        tempRole2.roleName = recipient2RoleName;
        tempRole2.name = recipient2FullName;
        tempRole2.email = recipient2Email;

        var signer3 = new docusign.Signer();
        signer3.email = recipient3Email;
        signer3.name = recipient3FullName;
        signer3.recipientId = '3';

        var tempRole3 = new docusign.TemplateRole();
        tempRole3.roleName = recipient3RoleName;
        tempRole3.name = recipient3FullName;
        tempRole3.email = recipient3Email;

        var signer4 = new docusign.Signer();
        signer4.email = recipient4Email;
        signer4.name = recipient4FullName;
        signer4.recipientId = '4';

        var tempRole4 = new docusign.TemplateRole();
        tempRole4.roleName = recipient4RoleName;
        tempRole4.name = recipient4FullName;
        tempRole4.email = recipient4Email;

        //TODO add the new template roles to the templateRolesList
        // create a list of template roles and add our newly created role
        var templateRolesList = [];
        templateRolesList.push(tempRole1);
        templateRolesList.push(tempRole2);
        templateRolesList.push(tempRole3);
        templateRolesList.push(tempRole4);

        // assign template role(s) to the envelope
        envDef.templateRoles = templateRolesList;

        //set the values of the text tabs in the envelope
        var tabs = new docusign.Tabs();
        tabs.textTabs = getTextTabs(selectedRow);

        //envDef.recipients = new docusign.Recipients();
        //envDef.recipients.signers = [];
        //envDef.recipients.signers.push(signer1);
        //envDef.recipients.signers.push(signer2);
        //envDef.recipients.signers.push(signer3);
        //envDef.recipients.signers.push(signer4);

        tempRole1.tabs = tabs;
        tempRole2.tabs = tabs;
        tempRole3.tabs = tabs;
        tempRole4.tabs = tabs;

        // send the envelope by setting |status| to 'sent'. To save as a draft set to 'created'
        envDef.status = 'sent';

        // use the |accountId| we retrieved through the Login API to create the Envelope
        var accountId = loginAccount.accountId;

        // instantiate a new EnvelopesApi object
        var envelopesApi = new docusign.EnvelopesApi();

        return envelopesApi.createEnvelope(accountId, { 'envelopeDefinition': envDef }, afterCreateEnvelope);
    }

    function afterCreateEnvelope(err, envelopeSummary, response) {
        if (err) {
            return callback(err, null, null);
        } else {
            return callback(null, envelopeSummary, response);
        }
    }
}

I have to create a DocuSign envelope for every row of data (there is a grid in the UI I created), if I step into authApi.login() and F10 down to line 246 (return this.apiClient.callApi()) and F10 once more, my callbacks are fulfilled, the row of data archives the way its supposed to, it send the envelope like its supposed to, it works, but ONLY if I step over this line.

If I run the application this is used in without debugging, the callbacks arent fulfilled, the envelope isnt created or sent, and the row of data never archives. Where did I go wrong? Or is the package that's out there not supporting callbacks? Is there a way to set a timeout for this? I've tried setTimeout() and it doesnt work. I've tried using promises, still doesnt work.

I know there has to be a way to do multiple actions when using the docusign-node-client coupled with whatever loads of work I have to do. It cant be that you have to do everything with DocuSign separate from whatever else you have to do.

**Comment by ECDonelson** [comment]
Also my code wont format correctly

**Comment by LarryKlugerDS** [comment]
I apologize for the delays in responding to your question. We've reorganized so we can answer your questions quicker. In addition, StackOverflow with the `docusignapi` tag is usually the best place to get these types of questions answered.

In your specific case, I suggest switching to using the Node.js SDK with promises. They're much easier to use than dealing with callback hell. And even better is to use the Node.js 8.x Long Term Support (LTS) release. It includes support for `await`. See my [blog post](https://www.docusign.com/blog/dsdev-node-promises/) about this.

Finally, here's a set of code examples which use promises: https://github.com/docusign/eg-03-node-auth-code-grant
