### ISSUE TITLE
ApiClient.configureJWTAuthorizationFlow assumes reading privatekey from local file  

### ISSUE THREAD

**Issue by ArindamRayMukherjee** [docusign/docusign-node-client#89]
*configureJWTAuthorizationFlow* does *fs.readFileSync(privateKeyFilename)*.
Sometimes the contents of the key might be stored in a cloud based key vault and thus might be useful to have this injectable as a buffer.

**Comment by ArindamRayMukherjee** [comment]
`  /**
   * Configures the current instance of ApiClient with a fresh OAuth JWT access token from DocuSign
   * @param privateKey the buffer containing the RSA private key
   * @param oAuthBasePath DocuSign OAuth base path (account-d.docusign.com for the developer sandbox
   *            and account.docusign.com for the production platform)
   * @param clientId DocuSign OAuth Client Id (AKA Integrator Key)
   * @param userId DocuSign user Id to be impersonated (This is a UUID)
   * @param expiresIn in seconds for the token time-to-live
   * @param callback the callback function.
   */
  exports.prototype.configureJWTAuthFlowKeyBuf = function configureJWTAuthFlowKeyBuf(privateKey, oAuthBasePath, clientId, userId, expiresIn, callback) {
    var _this = this;
    var jwt = require('jsonwebtoken')
      , now = Math.floor(Date.now() / 1000)
      , later = now + expiresIn;

    var jwt_payload = {
      iss: clientId,
      sub: userId,
      aud: oAuthBasePath,
      iat: now,
      exp: later,
      scope: "signature"
    };

    var assertion = jwt.sign(jwt_payload, privateKey, {algorithm: 'RS256'});

    superagent('post', 'https://' + oAuthBasePath + '/oauth/token')
      .timeout(this.timeout)
      .set('Content-Type', 'application/x-www-form-urlencoded')
      .send({
        'assertion': assertion,
        'grant_type': 'urn:ietf:params:oauth:grant-type:jwt-bearer'
      })
      .end(function (err, res) {
        if (callback) {
          if (!err && res.body && res.body.access_token) {
            _this.addDefaultHeader('Authorization', 'Bearer ' + res.body.access_token);
          }
          callback(err, res);
        }
      });
  };

  /**
   * Configures the current instance of ApiClient with a fresh OAuth JWT access token from DocuSign
   * @param privateKeyFilename the filename of the RSA private key
   * @param oAuthBasePath DocuSign OAuth base path (account-d.docusign.com for the developer sandbox
   *            and account.docusign.com for the production platform)
   * @param clientId DocuSign OAuth Client Id (AKA Integrator Key)
   * @param userId DocuSign user Id to be impersonated (This is a UUID)
   * @param expiresIn in seconds for the token time-to-live
   * @param callback the callback function.
   */
  exports.prototype.configureJWTAuthorizationFlow = function (privateKeyFilename, oAuthBasePath, clientId, userId, expiresIn, callback) {
    var _this = this;
    var fs = require('fs')
      , private_key = fs.readFileSync(privateKeyFilename);
    _this.configureJWTAuthFlowKeyBuf(private_key, oAuthBasePath, clientId, userId, expiresIn, callback);
  };`

**Comment by LarryKlugerDS** [comment]
An excellent enhancement request. Though it will need to be done carefully so it isn't a breaking changed. I've filed internal DocuSIgn enhancement request DCM-2274 so it can be considered.

**Comment by ArindamRayMukherjee** [comment]
Thanks!
```Though it will need to be done carefully so it isn't a breaking changed.```
To that end I kept the function name configureJWTAuthorizationFlow for the original functionality so that the change remains backwards compatible.

**Comment by conradob** [comment]
Looking forward for this because in the version 2 it was able to use the key from env variable now I can't upgrade to version 4 without a _"bandaid"_ for it. Any feedback?

**Comment by acooper4960** [comment]
Hi Folks, 
We have a new RC out that is changing the way we handle JWT. Please refer to version 4.1.0-rc1 for more info. You can download it via:`npm install docusign-esign@next` or wait until we have it released soon.

We are deprecating the legacy configureJWTAuthorizationFlow in favor of a more simple and secure function, requestJWTUserToken.

The preferred method for passing your private keys will be via buffer, not filename.

Please post here if you have any questions or concerns regarding this topic.

**Comment by acooper4960** [comment]
Update - the RC is now live, configureJWTAuthorizationFlow has been marked deprecated.

**Comment by acooper4960** [comment]
Closing as v4.1.0 is live
