### ISSUE TITLE
CANNOT_EXCLUDE_DOCUMENT Error createEnvelope API with Composite Templates 

### ISSUE THREAD

**Issue by ranjeshenboarder** [docusign/docusign-node-client#92]
Using documentation at createEnvelope with composite templates
https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/create/
https://developers.docusign.com/esign-rest-api/guides/features/templates

When we attempt to use this API for multiple templates we are getting error similar to below
{\r\n  \"errorCode\": \"CANNOT_EXCLUDE_DOCUMENT\",\r\n  \"message\": \"This document cannot be excluded for this recipient. Recipient: Enbmgr Enbmgr cannot be excluded from Document:TalentEmploymentAgreemt_0617AqVT.pdf\"\r\n}"}}
When the sequence of the templates are changed it works fine. What could be the cause for this?

The account is set up with Document Visibity: Sender can set "must sign to view unless sender"

Error when sent with below sequence
1) Templateid- f09dc354-efd6-437e-9410-5270b181a1f1 Roles: Emp, Mgr (sign in sequence enabled)
2) Templateid- 8c919c05-ee1f-42c4-b521-861c5f2949b Roles: Emp
3) Templateid- 6b57ea78-5923-4c54-b4c1-15c8d5313e71 Roles: Emp, Mgr (sign in sequence enabled)

Success when sent with below sequence
C) Templateid- 6b57ea78-5923-4c54-b4c1-15c8d5313e71 Roles: Emp, Mgr (sign in sequence enabled)
A) Templateid- f09dc354-efd6-437e-9410-5270b181a1f1 Roles: Emp, Mgr (sign in sequence enabled)
B) Templateid- 8c919c05-ee1f-42c4-b521-861c5f2949b Roles: Emp

Request giving error 
{
  "emailSubject": "DocuSign API - Composite Templates",
  "emailBlurb": "Composite Templates Sample 1",
  "status": "sent",
  "compositeTemplates": [
    [
      {
        "serverTemplates": [
          {
            "sequence": "1",
            "templateId": "f09dc354-efd6-437e-9410-5270b181a1f1"
          }
        ],
        "inlineTemplates": [
          {
            "sequence": "2",
            "recipients": {
              "signers": [
                {
                  "email": "ranjesh+emp@enboarder.com",
                  "name": "Enbemp Enbemp",
                  "roleName": "Talent",
                  "recipientId": "1",
                  "tabs": {}
                },
                {
                  "email": "ranjesh+mgr@enboarder.com",
                  "name": "Enbmgr Enbmgr",
                  "roleName": "OM",
                  "recipientId": "2",
                  "tabs": {}
                }
              ]
            }
          }
        ]
      },
      {
        "serverTemplates": [
          {
            "sequence": "3",
            "templateId": "8c919c05-ee1f-42c4-b521-861c5f2949bf"
          }
        ],
        "inlineTemplates": [
          {
            "sequence": "4",
            "recipients": {
              "signers": [
                {
                  "email": "ranjesh+emp@enboarder.com",
                  "name": "Enbemp Enbemp",
                  "roleName": "Talent",
                  "recipientId": "1",
                  "tabs": {
                    "textTabs": [
                      {
                        "tabLabel": "\\*Market",
                        "value": " "
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      },
      {
        "serverTemplates": [
          {
            "sequence": "5",
            "templateId": "6b57ea78-5923-4c54-b4c1-15c8d5313e71"
          }
        ],
        "inlineTemplates": [
          {
            "sequence": "6",
            "recipients": {
              "signers": [
                {
                  "email": "ranjesh+emp@enboarder.com",
                  "name": "Enbemp Enbemp",
                  "roleName": "Talent",
                  "recipientId": "1",
                  "tabs": {}
                },
                {
                  "email": "ranjesh+mgr@enboarder.com",
                  "name": "Enbmgr Enbmgr",
                  "roleName": "OM",
                  "recipientId": "2",
                  "tabs": {}
                }
              ]
            }
          }
        ]
      }
    ]
  ]
}
Request giving success
{
  "emailSubject": "DocuSign API - Composite Templates",
  "emailBlurb": "Composite Templates Sample 1",
  "status": "sent",
  "compositeTemplates": [
    [
      {
        "serverTemplates": [
          {
            "sequence": "1",
            "templateId": "6b57ea78-5923-4c54-b4c1-15c8d5313e71"
          }
        ],
        "inlineTemplates": [
          {
            "sequence": "2",
            "recipients": {
              "signers": [
                {
                  "email": "ranjesh+emp@enboarder.com",
                  "name": "Enbemp Enbemp",
                  "roleName": "Talent",
                  "recipientId": "1",
                  "tabs": {}
                },
                {
                  "email": "ranjesh+mgr@enboarder.com",
                  "name": "Enbmgr Enbmgr",
                  "roleName": "OM",
                  "recipientId": "2",
                  "tabs": {}
                }
              ]
            }
          }
        ]
      },
      {
        "serverTemplates": [
          {
            "sequence": "3",
            "templateId": "f09dc354-efd6-437e-9410-5270b181a1f1"
          }
        ],
        "inlineTemplates": [
          {
            "sequence": "4",
            "recipients": {
              "signers": [
                {
                  "email": "ranjesh+emp@enboarder.com",
                  "name": "Enbemp Enbemp",
                  "roleName": "Talent",
                  "recipientId": "1",
                  "tabs": {}
                },
                {
                  "email": "ranjesh+mgr@enboarder.com",
                  "name": "Enbmgr Enbmgr",
                  "roleName": "OM",
                  "recipientId": "2",
                  "tabs": {}
                }
              ]
            }
          }
        ]
      },
      {
        "serverTemplates": [
          {
            "sequence": "5",
            "templateId": "8c919c05-ee1f-42c4-b521-861c5f2949bf"
          }
        ],
        "inlineTemplates": [
          {
            "sequence": "6",
            "recipients": {
              "signers": [
                {
                  "email": "ranjesh+emp@enboarder.com",
                  "name": "Enbemp Enbemp",
                  "roleName": "Talent",
                  "recipientId": "1",
                  "tabs": {
                    "textTabs": [
                      {
                        "tabLabel": "\\*Market",
                        "value": " "
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    ]
  ]
}

**Comment by LarryKlugerDS** [comment]
Re: why does one give an error?

In the JSON with the error, the second composite template does not set the signer for role `OM`. You need to set a recipient value for each role in the server template.

Re: When the sequence of the templates are changed it works fine. What could be the cause for this?

This is how composite templates work--order (as determined by sequence number and array placement) of later templates, either server or inline, "provide" data to the overall composite template that is being built up. 

So if a template has a role, then a **later** template must provide the data (the signer information) for that role.

I also see various issues for both JSON structures:

* Array of arrays instead of Array of objects
  The compositeTemplates attribute should be set to an array of CompositeTemplate objects. But instead, you're setting it to an array of an array of objects.

````
You're doing this:

  "compositeTemplates": [
    [
      {
        "serverTemplates": [

But you should be doing this:
  "compositeTemplates": [
      {
        "serverTemplates": [
````

* Note that each CompositeTemplate stands on its own. So the `sequence` numbers can be restarted for each individual  CompositeTemplate.

* Set a `compositeTemplateId` for each individual composite template to help keep things straight and hopefully receive better error messages.

I'm glad you got it working. And I apologize for the slow reply. We're organizing to get you answers sooner. Also, this is a great type of question for our `docusignapi` tag on stackoverflow.
