### ISSUE TITLE
How to revokeOAuthToken?

### ISSUE THREAD

**Issue by teebu** [docusign/docusign-node-client#95]
I'm logged in, and able to get results from other calls, but I can't seem to be able to revoke oauth. 

I'm also getting the same message in api explorer. 

I'm getting this message: 
```
Exception! Result: Error: Bad Request. API error message: {"error":"invalid_token","error_description":"The presented token is invalid."}

```

code:
```
function revokeOAuthToken() {

	// instantiate a new AuthenticationApi object
	let authenticationApi = new docusign.AuthenticationApi;
	// Promises are more convenient, so we promisfy it.
	let revokeOAuthToken_promise = make_promise(authenticationApi, 'revokeOAuthToken');
	console.log(authenticationApi.revokeOAuthToken.toString())
	return (
		revokeOAuthToken_promise()
			.then ((result) => {
				console.log(`\nrevokeOAuthToken!`);
				return result;
			})
			.catch ((err) => {
				// If the error is from DocuSign, the actual error body is available in err.response.body
				let errMsg = err.response && err.response.body && JSON.stringify(err.response.body)
					, msg = `\nException! Result: ${err}`;
				if (errMsg) {
					msg += `. API error message: ${errMsg}`;
				}
				console.log(msg);
				return {msg: msg};
			})
	)
}
```

**Comment by 7assenTlili** [comment]
I am getting a similar error for the getOAuthToken() function.

**Comment by LarryKlugerDS** [comment]
The methods in the [Authentication](https://developers.docusign.com/esign-rest-api/reference/Authentication/Authentication) resource are all **obsolete** and should not be used.

Instead, use our OAuth2 methods/end points. For Node.js, see the [Authorization Code Grant](https://github.com/docusign/eg-03-node-auth-code-grant) example. 

I have filed documentation internal ticket DEVDOCS-678 to have the methods removed from the documentation. Also, I apologize for the very slow response on your issue. We've re-organized to improve our responsiveness.
