### ISSUE TITLE
All calls result in HTTP 401 

### ISSUE THREAD

**Issue by bradvogel** [docusign/docusign-node-client#98]
I must be missing something here - I don't see how authentication works for any of the calls. For example, take the following example code:

```
      const connectAPI = new docusign.ConnectApi(apiClient);
      connectAPI.listConfigurations('67555807-a122-4a36-bd72-67fe81325bd', (err, data) => {
        console.log(err, data)
      });
```

It always results in an HTTP 401 since the access token is never sent. Digging into the source a bit, it looks like `authNames` is hardcoded to an empty array: https://github.com/docusign/docusign-node-client/blob/529d5e15f83909a8309cf51972164b93d5f47e2f/src/api/ConnectApi.js#L515

which means that no auth token is ever sent with the call. This code doesn't seem right.

How can I call listConfigurations successfully if I have an oauth2 auth token?

**Comment by mmallis87** [comment]
If you're planning on using Authorization code grant, then this is an example: https://github.com/docusign/docusign-node-client#sdk-version-3xx

All authentication methods are set at ApiClient.js. In case you haven't seen it yet. The quickstart guide has everything you need in order to get started: https://developers.docusign.com/esign-rest-api/guides

**Comment by bradvogel** [comment]
Thanks - I've seen those. But from what I see in the source of this module, it's impossible to ever call `connectAPI.listConfigurations()` successfully. The auth token is never added to the payload under any circumstance. Can you provide an example where that method can be successfully called?

**Comment by acooper4960** [comment]
Hi @bradvogel, have you tried adding your auth token as a default header to your apiClient prior to initializing your ConnectAPI?
apiClient.addDefaultHeader('Authorization', 'Bearer ' + res.body.access_token);

**Comment by bradvogel** [comment]
oh I see - that's very hidden. A code example in the readme would help, since that line is required for any API call

**Comment by acooper4960** [comment]
This has now been added to the two non JWT examples. Hope that helps!
